/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.*;
import java.awt.event.*;
import static java.lang.Boolean.FALSE;
import static java.lang.Boolean.TRUE;
import javax.swing.*;

/**
 *
 * @author karol
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tela = new javax.swing.JPanel();
        btnLivros = new javax.swing.JButton();
        btnAutores = new javax.swing.JButton();
        btnEditoras = new javax.swing.JButton();
        btnLocacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Biblioteca"); // NOI18N

        btnLivros.setText("Livros");
        btnLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivrosActionPerformed(evt);
            }
        });

        btnAutores.setText("Autores");
        btnAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoresActionPerformed(evt);
            }
        });

        btnEditoras.setText("Editoras");
        btnEditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorasActionPerformed(evt);
            }
        });

        btnLocacao.setText("Locação");
        btnLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);
        telaLayout.setHorizontalGroup(
            telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditoras, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        telaLayout.setVerticalGroup(
            telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(btnLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnEditoras, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void removeFromWindowMenuGroup() {
        this.tela.removeAll();
        this.tela.revalidate();
        this.tela.repaint();
    }

    /*Botões de ações dos livros*/

    private void btnLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivrosActionPerformed
        // TODO add your handling code here:
        removeFromWindowMenuGroup();
        livrosWindow();
    }//GEN-LAST:event_btnLivrosActionPerformed

    private void btnLivroCadActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        removeFromWindowMenuGroup();
        livroCadWindow();
    }

    private void btnLivroVisuActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        removeFromWindowMenuGroup();
        livroVisuWindow();
    }
    
    private void btnCadLivroActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        String autorLivro = this.inputAutor.getText();
        String tituloLivro = this.inputTitulo.getText();
        String editoraLivro = this.inputEditora.getText();

        if (autorLivro.equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo autor!");
        } else if (tituloLivro.equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo título!");
        } else {
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
            removeFromWindowMenuGroup();
            livrosWindow();
        }

    }

    /*Botões de ações dos autores*/

    private void btnAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoresActionPerformed
        // TODO add your handling code here:
        removeFromWindowMenuGroup();
        autoresWindow();
    }//GEN-LAST:event_btnAutoresActionPerformed

    private void btnAutorCadActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        removeFromWindowMenuGroup();
        autorCadWindow();
    }
    
    private void btnAutorVisuActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        removeFromWindowMenuGroup();
        autorVisuWindow();
    }

    private void btnCadAutorActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        String nomeAutor = this.inputNomeAutor.getText();

        if (nomeAutor.equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo autor!");
        } 
        else {
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
            removeFromWindowMenuGroup();
            autoresWindow();
        }

    }
    
    /*Botões de ações das editoras*/
    
    private void btnEditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorasActionPerformed
        // TODO add your handling code here:
        removeFromWindowMenuGroup();
        editorasWindow();
    }//GEN-LAST:event_btnEditorasActionPerformed

    private void btnLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocacaoActionPerformed
        // TODO add your handling code here:
        removeFromWindowMenuGroup();
        locacaoWindow();
    }//GEN-LAST:event_btnLocacaoActionPerformed

    private void btnEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        removeFromWindowMenuGroup();
        emprestimoWindow();
    }  
    
    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        removeFromWindowMenuGroup();
        reservaWindow();
    }  
    
    private void btnCadEditoraActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        // TODO add your handling code here:

        String nomeEditora = this.inputNomeEditora.getText();

        if (nomeEditora.equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo autor!");
        } 
        else {
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
            removeFromWindowMenuGroup();
            editorasWindow();
        }
    }
    
    private void btnEditoraCadActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        removeFromWindowMenuGroup();
        editoraCadWindow();
    }
    
    private void btnEditoraVisuActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        removeFromWindowMenuGroup();
        editoraVisuWindow();
    }
    
    private void voltarMenuPrincActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        removeFromWindowMenuGroup();
        menuPrincipalWindow();
    }

    private void voltarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        removeFromWindowMenuGroup();
        locacaoWindow();
    }
    
    /*Janelas*/
    private void menuPrincipalWindow() {
        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);
        telaLayout.setHorizontalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaLayout.createSequentialGroup()
                                .addContainerGap(63, Short.MAX_VALUE)
                                .addGroup(telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(btnLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEditoras, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58))
        );
        telaLayout.setVerticalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaLayout.createSequentialGroup()
                                .addContainerGap(50, Short.MAX_VALUE)
                                .addComponent(btnLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnEditoras, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }
    
    /* Livros */
    public void livrosWindow() {
        this.btnLivroCad = new javax.swing.JButton();
        this.btnLivroAt = new javax.swing.JButton();
        this.btnLivroRem = new javax.swing.JButton();
        this.btnLivroVisu = new javax.swing.JButton();

        this.voltarMenuPrinc = new javax.swing.JButton();

        this.btnLivroCad.setText("Cadastrar Livro");
        btnLivroCad.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnLivroCadActionPerformed(evt);
        });

        this.btnLivroAt.setText("Atualizar Livro");
        this.btnLivroRem.setText("Remover Livro");
        
        this.btnLivroVisu.setText("Visualizar Livro");
        btnLivroVisu.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnLivroVisuActionPerformed(evt);
        });

        this.voltarMenuPrinc.setText("Voltar");
        voltarMenuPrinc.addActionListener((java.awt.event.ActionEvent evt) -> {
            voltarMenuPrincActionPerformed(evt);
        });

        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);

        telaLayout.setHorizontalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaLayout.createSequentialGroup()
                                .addContainerGap(63, Short.MAX_VALUE)
                                .addGroup(telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(btnLivroCad, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnLivroAt, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnLivroRem, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnLivroVisu, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58))
                        .addGroup(telaLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(voltarMenuPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaLayout.setVerticalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaLayout.createSequentialGroup()
                                .addContainerGap(72, Short.MAX_VALUE)
                                .addComponent(btnLivroCad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnLivroAt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnLivroRem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnLivroVisu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(voltarMenuPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    public void livroCadWindow() {
        labelTitulo = new javax.swing.JLabel();
        this.inputTitulo = new javax.swing.JTextField();
        labelAutor = new javax.swing.JLabel();
        this.inputAutor = new javax.swing.JTextField();
        labelEditora = new javax.swing.JLabel();
        this.inputEditora = new javax.swing.JTextField();

        labelCadastrarLivro = new javax.swing.JLabel();
        btnCadLivro = new javax.swing.JButton();

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTitulo.setText("Título");

        labelAutor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelAutor.setText("Autor");

        labelEditora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelEditora.setText("Editora");

        labelCadastrarLivro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelCadastrarLivro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCadastrarLivro.setText("Cadastrar Livro");

        this.btnCadLivro.setText("Cadastrar");
        btnCadLivro.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnCadLivroActionPerformed(evt);
        });

        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);
        telaLayout.setHorizontalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaLayout.createSequentialGroup()
                                .addComponent(labelCadastrarLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                        .addGroup(telaLayout.createSequentialGroup()
                                .addGroup(telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(telaLayout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addGroup(telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(this.inputAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                        .addComponent(labelAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(this.inputTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                        .addComponent(labelEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(this.inputEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                ).addGap(50, 50, 50))
                                        .addGroup(telaLayout.createSequentialGroup()
                                                .addGap(220, 220, 220)
                                                .addComponent(btnCadLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaLayout.setVerticalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(labelCadastrarLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(labelAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(labelEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(btnCadLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>    
    
    public void livroVisuWindow(){
        labelExibirLivro = new javax.swing.JLabel();
        areaTextExibirLivro = new javax.swing.JTextArea(15, 70);
        
        
        scrollBarExibirLivro = new javax.swing.JScrollPane(areaTextExibirLivro);
        
        
        scrollBarExibirLivro.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollBarExibirLivro.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollBarExibirLivro.setBounds(50, 30, 500, 100);
        
        String listaLivros = "";
        
        labelExibirLivro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelExibirLivro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelExibirLivro.setText("Visualizar Livros");
        
        areaTextExibirLivro.append(listaLivros);
        areaTextExibirLivro.setEditable(false);
        
        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);
        telaLayout.setHorizontalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaLayout.createSequentialGroup()
                                .addComponent(labelExibirLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                        .addGroup(telaLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(scrollBarExibirLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                .addGap(60, 60, 60))
        );
        telaLayout.setVerticalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(labelExibirLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(scrollBarExibirLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }
    
    /* Autores */
    public void autoresWindow() {
        this.btnAutorCad = new javax.swing.JButton();
        this.btnAutorAt = new javax.swing.JButton();
        this.btnAutorRem = new javax.swing.JButton();
        this.btnAutorVisu = new javax.swing.JButton();

        this.voltarMenuPrinc = new javax.swing.JButton();

        this.btnAutorCad.setText("Cadastrar Autor");
        this.btnAutorAt.setText("Atualizar Autor");
        this.btnAutorRem.setText("Remover Autor");
        this.btnAutorVisu.setText("Visualizar Autor");

        this.voltarMenuPrinc.setText("Voltar");
        voltarMenuPrinc.addActionListener((java.awt.event.ActionEvent evt) -> {
            voltarMenuPrincActionPerformed(evt);
        });

        btnAutorCad.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnAutorCadActionPerformed(evt);
        });
        
        btnAutorVisu.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnAutorVisuActionPerformed(evt);
        });

        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);

        telaLayout.setHorizontalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaLayout.createSequentialGroup()
                                .addContainerGap(63, Short.MAX_VALUE)
                                .addGroup(telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(btnAutorCad, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAutorAt, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAutorRem, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAutorVisu, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58))
                        .addGroup(telaLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(voltarMenuPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        telaLayout.setVerticalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaLayout.createSequentialGroup()
                                .addContainerGap(72, Short.MAX_VALUE)
                                .addComponent(btnAutorCad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnAutorAt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnAutorRem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnAutorVisu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(voltarMenuPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }                    

    public void autorCadWindow() {
        labelNomeAutor = new javax.swing.JLabel();
        inputNomeAutor = new javax.swing.JTextField();

        labelCadastrarAutor = new javax.swing.JLabel();
        btnCadAutor = new javax.swing.JButton();

        labelNomeAutor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNomeAutor.setText("Nome do Autor");

        labelCadastrarAutor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelCadastrarAutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCadastrarAutor.setText("Cadastrar Autor");

        this.btnCadAutor.setText("Cadastrar");
        btnCadAutor.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnCadAutorActionPerformed(evt);
        });

        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);
        telaLayout.setHorizontalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaLayout.createSequentialGroup()
                                .addComponent(labelCadastrarAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                        .addGroup(telaLayout.createSequentialGroup()
                                .addGroup(telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(telaLayout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addGroup(telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(this.inputNomeAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                        .addComponent(labelNomeAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                                ).addGap(50, 50, 50))
                                        .addGroup(telaLayout.createSequentialGroup()
                                                .addGap(220, 220, 220)
                                                .addComponent(btnCadAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaLayout.setVerticalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(labelCadastrarAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(labelNomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputNomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnCadAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }
    
    public void autorVisuWindow(){
        labelExibirAutor = new javax.swing.JLabel();
        areaTextExibirAutor = new javax.swing.JTextArea(15, 70);
        
        
        scrollBarExibirAutor = new javax.swing.JScrollPane(areaTextExibirAutor);
        
        
        scrollBarExibirAutor.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollBarExibirAutor.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollBarExibirAutor.setBounds(50, 30, 500, 100);
        
        String listaAutor = "";
        
        labelExibirAutor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelExibirAutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelExibirAutor.setText("Visualizar Autores");
        
        areaTextExibirAutor.append(listaAutor);
        areaTextExibirAutor.setEditable(false);
        
        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);
        telaLayout.setHorizontalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaLayout.createSequentialGroup()
                                .addComponent(labelExibirAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                        .addGroup(telaLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(scrollBarExibirAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                .addGap(60, 60, 60))
        );
        telaLayout.setVerticalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(labelExibirAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(scrollBarExibirAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }
    
    public void editorasWindow() {
        this.btnEditoraCad = new javax.swing.JButton();
        this.btnEditoraAt = new javax.swing.JButton();
        this.btnEditoraRem = new javax.swing.JButton();
        this.btnEditoraVisu = new javax.swing.JButton();

        this.voltarMenuPrinc = new javax.swing.JButton();

        this.btnEditoraCad.setText("Cadastrar Editora");
        this.btnEditoraAt.setText("Atualizar Editora");
        this.btnEditoraRem.setText("Remover Editora");
        this.btnEditoraVisu.setText("Visualizar Editora");

        this.voltarMenuPrinc.setText("Voltar");
        voltarMenuPrinc.addActionListener((java.awt.event.ActionEvent evt) -> {
            voltarMenuPrincActionPerformed(evt);
        });
        
        btnEditoraCad.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnEditoraCadActionPerformed(evt);
        });

        btnEditoraVisu.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnEditoraVisuActionPerformed(evt);
        });
        
        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);

        telaLayout.setHorizontalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaLayout.createSequentialGroup()
                                .addContainerGap(63, Short.MAX_VALUE)
                                .addGroup(telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(btnEditoraCad, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEditoraAt, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEditoraRem, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEditoraVisu, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58))
                        .addGroup(telaLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(voltarMenuPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        telaLayout.setVerticalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaLayout.createSequentialGroup()
                                .addContainerGap(72, Short.MAX_VALUE)
                                .addComponent(btnEditoraCad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnEditoraAt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnEditoraRem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnEditoraVisu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(voltarMenuPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }
    
    public void editoraCadWindow() {
        labelNomeEditora = new javax.swing.JLabel();
        inputNomeEditora = new javax.swing.JTextField();

        labelCadastrarEditora = new javax.swing.JLabel();
        btnCadEditora = new javax.swing.JButton();

        labelNomeEditora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNomeEditora.setText("Nome da Editora");

        labelCadastrarEditora.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelCadastrarEditora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCadastrarEditora.setText("Cadastrar Editora");

        this.btnCadEditora.setText("Cadastrar");
        btnCadEditora.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnCadEditoraActionPerformed(evt);
        });

        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);
        telaLayout.setHorizontalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaLayout.createSequentialGroup()
                                .addComponent(labelCadastrarEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                        .addGroup(telaLayout.createSequentialGroup()
                                .addGroup(telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(telaLayout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addGroup(telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(this.inputNomeEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                        .addComponent(labelNomeEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                                ).addGap(50, 50, 50))
                                        .addGroup(telaLayout.createSequentialGroup()
                                                .addGap(220, 220, 220)
                                                .addComponent(btnCadEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaLayout.setVerticalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(labelCadastrarEditora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(labelNomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputNomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnCadEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>         
    
    public void editoraVisuWindow(){
        labelExibirEditora = new javax.swing.JLabel();
        areaTextExibirEditora = new javax.swing.JTextArea(15, 70);
        
        
        scrollBarExibirEditora = new javax.swing.JScrollPane(areaTextExibirEditora);
        
        
        scrollBarExibirEditora.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollBarExibirEditora.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollBarExibirEditora.setBounds(50, 30, 500, 100);
        
        String listaAutor = "";
        
        labelExibirEditora.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelExibirEditora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelExibirEditora.setText("Visualizar Editoras");
        
        areaTextExibirEditora.append(listaAutor);
        areaTextExibirEditora.setEditable(false);
        
        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);
        telaLayout.setHorizontalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaLayout.createSequentialGroup()
                                .addComponent(labelExibirEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                        .addGroup(telaLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(scrollBarExibirEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                .addGap(60, 60, 60))
        );
        telaLayout.setVerticalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(labelExibirEditora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(scrollBarExibirEditora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }
    
    /*Locações */
    
    public void locacaoWindow() {
        this.btnEmprestimo = new javax.swing.JButton();
        this.btnReserva = new javax.swing.JButton();

        this.voltarMenuPrinc = new javax.swing.JButton();

        this.btnEmprestimo.setText("Emprestimo");
        
        btnEmprestimo.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnEmprestimoActionPerformed(evt);
        });
        
        this.btnReserva.setText("Reserva");
        
        btnReserva.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnReservaActionPerformed(evt);
        });
        
        this.voltarMenuPrinc.setText("Voltar");
        voltarMenuPrinc.addActionListener((java.awt.event.ActionEvent evt) -> {
            voltarMenuPrincActionPerformed(evt);
        });

        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);

        telaLayout.setHorizontalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaLayout.createSequentialGroup()
                                .addContainerGap(63, Short.MAX_VALUE)
                                .addGroup(telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(btnEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                )
                        .addGroup(telaLayout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(voltarMenuPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        telaLayout.setVerticalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaLayout.createSequentialGroup()
                                .addContainerGap(72, Short.MAX_VALUE)
                                .addComponent(btnEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(voltarMenuPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }
    
    public void emprestimoWindow() {
        btnSolicitarEmprestimo = new javax.swing.JButton();
        btnHistoricoEmprestimo = new javax.swing.JButton();
        btnAcompanharEmprestimo = new javax.swing.JButton();
        btnCancelarEmprestimo = new javax.swing.JButton();
        
        this.voltarLocacao = new javax.swing.JButton();

        this.btnSolicitarEmprestimo.setText("Solicitar Emprestimo");
        this.btnHistoricoEmprestimo.setText("Historico de Emprestimos");
        this.btnAcompanharEmprestimo.setText("Acompanhar Emprestimo");
        this.btnCancelarEmprestimo.setText("Cancelar Emprestimo");
        
        this.voltarLocacao.setText("Voltar");
        voltarLocacao.addActionListener((java.awt.event.ActionEvent evt) -> {
            voltarLocacaoActionPerformed(evt);
        });

        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);

        telaLayout.setHorizontalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaLayout.createSequentialGroup()
                                .addContainerGap(63, Short.MAX_VALUE)
                                .addGroup(telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(btnSolicitarEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnHistoricoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAcompanharEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCancelarEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                )
                        .addGroup(telaLayout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(voltarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        telaLayout.setVerticalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaLayout.createSequentialGroup()
                                .addContainerGap(72, Short.MAX_VALUE)
                                .addComponent(btnSolicitarEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnHistoricoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnAcompanharEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnCancelarEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(voltarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }
    
    public void reservaWindow() {
        btnSolicitarReserva = new javax.swing.JButton();
        btnHistoricoReserva = new javax.swing.JButton();
        btnAcompanharReserva = new javax.swing.JButton();
        btnCancelarReserva = new javax.swing.JButton();
        
        this.voltarLocacao = new javax.swing.JButton();

        this.btnSolicitarReserva.setText("Solicitar Reserva");
        this.btnHistoricoReserva.setText("Historico de Reservas");
        this.btnAcompanharReserva.setText("Acompanhar Reserva");
        this.btnCancelarReserva.setText("Cancelar Reserva");
        
        this.voltarLocacao.setText("Voltar");
        voltarLocacao.addActionListener((java.awt.event.ActionEvent evt) -> {
            voltarLocacaoActionPerformed(evt);
        });

        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);

        telaLayout.setHorizontalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaLayout.createSequentialGroup()
                                .addContainerGap(63, Short.MAX_VALUE)
                                .addGroup(telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(btnSolicitarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnHistoricoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAcompanharReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCancelarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                )
                        .addGroup(telaLayout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(voltarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        telaLayout.setVerticalGroup(
                telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(telaLayout.createSequentialGroup()
                                .addContainerGap(72, Short.MAX_VALUE)
                                .addComponent(btnSolicitarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnHistoricoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnAcompanharReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnCancelarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(voltarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutores;
    private javax.swing.JButton btnEditoras;
    private javax.swing.JButton btnLivros;
    private javax.swing.JButton btnLocacao;
    private javax.swing.JPanel tela;
    // End of variables declaration//GEN-END:variables

    //Botões Livro
    private javax.swing.JButton btnLivroCad;
    private javax.swing.JButton btnLivroAt;
    private javax.swing.JButton btnLivroRem;
    private javax.swing.JButton btnLivroVisu;

    //Botões Autores
    private javax.swing.JButton btnAutorCad;
    private javax.swing.JButton btnAutorAt;
    private javax.swing.JButton btnAutorRem;
    private javax.swing.JButton btnAutorVisu;

    //Botões Editoras
    private javax.swing.JButton btnEditoraCad;
    private javax.swing.JButton btnEditoraAt;
    private javax.swing.JButton btnEditoraRem;
    private javax.swing.JButton btnEditoraVisu;

    //Botões Locações
    private javax.swing.JButton btnEmprestimo;
    private javax.swing.JButton btnReserva;
    
    /*Locações Opções*/
    
    //Emprestimo
    private javax.swing.JButton btnSolicitarEmprestimo;
    private javax.swing.JButton btnAcompanharEmprestimo;
    private javax.swing.JButton btnHistoricoEmprestimo;
    private javax.swing.JButton btnCancelarEmprestimo;
    private javax.swing.JButton voltarLocacao;
    
    //Reserva
    private javax.swing.JButton btnSolicitarReserva;
    private javax.swing.JButton btnAcompanharReserva;
    private javax.swing.JButton btnHistoricoReserva;
    private javax.swing.JButton btnCancelarReserva;
    
    //Outros elementos
    private javax.swing.JButton voltarMenuPrinc;

    /*Livro opções*/
    //Cadastrar
    private javax.swing.JTextField inputAutor;
    private javax.swing.JTextField inputTitulo;
    private javax.swing.JTextField inputEditora;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelEditora;
    private javax.swing.JLabel labelCadastrarLivro;
    private javax.swing.JButton btnCadLivro;
    
    //Exibir
    private javax.swing.JLabel labelExibirLivro;
    private javax.swing.JScrollPane scrollBarExibirLivro;
    private javax.swing.JTextArea areaTextExibirLivro;
    
    /*Autor opções*/
    //Cadastrar
    private javax.swing.JTextField inputNomeAutor;
    private javax.swing.JLabel labelNomeAutor;
    private javax.swing.JButton btnCadAutor;
    private javax.swing.JLabel labelCadastrarAutor;
    
    //Exibir
    private javax.swing.JLabel labelExibirAutor;
    private javax.swing.JScrollPane scrollBarExibirAutor;
    private javax.swing.JTextArea areaTextExibirAutor;
    
    /*Editora opções*/
    //Cadastrar
    private javax.swing.JTextField inputNomeEditora;
    private javax.swing.JLabel labelNomeEditora;
    private javax.swing.JButton btnCadEditora;
    private javax.swing.JLabel labelCadastrarEditora;
    
    //Exibir
    private javax.swing.JLabel labelExibirEditora;
    private javax.swing.JScrollPane scrollBarExibirEditora;
    private javax.swing.JTextArea areaTextExibirEditora;
}
